apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tg8fnsknv-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tg8fnsknv-java-quarkus-gitops